https://es.investing.com/stock-screener/?sp=country::29|sector::a|industry::a|equityType::a%3Ceq_market_cap;1


https://es.investing.com/equities/ypf-sociedad
https://es.investing.com/equities/gp-fin-galicia
https://es.investing.com/equities/macro
https://es.investing.com/equities/b-santander-ri
https://es.investing.com/equities/mirgor
https://es.investing.com/equities/frances
https://es.investing.com/equities/pampa-energia
https://es.investing.com/equities/siderar
https://es.investing.com/equities/telecom
https://es.investing.com/equities/central-puerto
https://es.investing.com/equities/loma-negra-ba?cid=1055994
https://es.investing.com/equities/loma-negra-ba
https://es.investing.com/equities/petrobras-arg
https://es.investing.com/equities/bco-patagonia
https://es.investing.com/equities/aluar
https://es.investing.com/equities/ferrum
https://es.investing.com/equities/grupo-supervielle-sa
https://es.investing.com/equities/juan-minetti
https://es.investing.com/equities/tran-gas-del-s
https://es.investing.com/equities/alto-palermo
https://es.investing.com/equities/irsa
https://es.investing.com/equities/camuzzi
https://es.investing.com/equities/edenor
https://es.investing.com/equities/consultatio-s.
https://es.investing.com/equities/bolsas-y-mercados-argentinos-sa
https://es.investing.com/equities/cresud
https://es.investing.com/equities/capex
https://es.investing.com/equities/metrogas
https://es.investing.com/equities/central-costan
https://es.investing.com/equities/i-y-e-de-la-pa
https://es.investing.com/equities/transener
https://es.investing.com/equities/comer-del-plat
https://es.investing.com/equities/molinos
https://es.investing.com/equities/gas-natural-sdg?cid=13343
https://es.investing.com/equities/bco-hipotecari
https://es.investing.com/equities/molinos-agro
https://es.investing.com/equities/boldt
https://es.investing.com/equities/grupo-financiero-valores
https://es.investing.com/equities/indupa
https://es.investing.com/equities/ledesma
https://es.investing.com/equities/con-del-oeste
https://es.investing.com/equities/inversora-juramento
https://es.investing.com/equities/bodegas-esmeralda-sa
https://es.investing.com/equities/san-miguel
https://es.investing.com/equities/ecogas
https://es.investing.com/equities/grupo-clarin
https://es.investing.com/equities/rigolleau
https://es.investing.com/equities/autopistas-sol
https://es.investing.com/equities/caputo
https://es.investing.com/equities/quickfood
https://es.investing.com/equities/grimoldi
https://es.investing.com/equities/nortel-inversora-sa
https://es.investing.com/equities/agrometal
https://es.investing.com/equities/celulosa
https://es.investing.com/equities/tglt-sa
https://es.investing.com/equities/dycasa
https://es.investing.com/equities/empresa-distribuidora-electrica
https://es.investing.com/equities/carlos-casado
https://es.investing.com/equities/compania-introductora-buenos-aires
https://es.investing.com/equities/longvie
https://es.investing.com/equities/insumos-agroquimicos-sa
https://es.investing.com/equities/moli-juan-semi
https://es.investing.com/equities/garovaglio
https://es.investing.com/equities/carboclor
https://es.investing.com/equities/fiplasto
https://es.investing.com/equities/pet.del-conosu
https://es.investing.com/equities/inst-rosembusc
https://es.investing.com/equities/morixe
https://es.investing.com/equities/domec-compania-de-artefactos-domest
https://es.investing.com/equities/colorin
https://es.investing.com/equities/polledo
https://es.investing.com/equities/caterpillar-inc-ar
https://es.investing.com/equities/microsoft-corp-ar
https://es.investing.com/equities/alcoa-inc.
https://es.investing.com/equities/walt-disney-company
https://es.investing.com/equities/cisco-systems
https://es.investing.com/equities/kimberly-clark-corp.
https://es.investing.com/equities/royal-dutch-shell-a-ar
https://es.investing.com/equities/koninklijke-philips-electronics
https://es.investing.com/equities/novartis-drc
https://es.investing.com/equities/total-cedear
https://es.investing.com/equities/banco-bilbao-vizcaya-argentaria
https://es.investing.com/equities/nokia
https://es.investing.com/equities/sap-ag-ads-exch?cid=30096
https://es.investing.com/equities/apple-inc.
https://es.investing.com/equities/rio-tinto-plc-exch?cid=30170
https://es.investing.com/equities/national-grid-ar
https://es.investing.com/equities/unilever-cert?cid=30183
https://es.investing.com/equities/pfizer-inc.-ar
https://es.investing.com/equities/bristol-myers-squibb-co.
https://es.investing.com/equities/yamana-gold-drc
https://es.investing.com/equities/hewlett-packard
https://es.investing.com/equities/china-mobile-ar
https://es.investing.com/equities/gazprom?cid=30359
https://es.investing.com/equities/barrick-gold
https://es.investing.com/equities/repsol-ypf?cid=13360
https://es.investing.com/equities/andes-energia-plc?cid=992998
https://es.investing.com/equities/petrobras-pn?cid=962554
https://es.investing.com/equities/american-express-co-ba
https://es.investing.com/equities/banco-santander-brasil-sa-ba
https://es.investing.com/equities/lockheed-martin-corp
https://es.investing.com/equities/mercadolibre-inc
https://es.investing.com/equities/banco-santander-rio-sa
https://es.investing.com/equities/ternium-s.a.?cid=962568
https://es.investing.com/equities/american-international-group-inc
https://es.investing.com/equities/alphabet-inc
https://es.investing.com/equities/honda?cid=962560
https://es.investing.com/equities/coca-cola-co-ba
https://es.investing.com/equities/petrolera-pampa-sa
https://es.investing.com/equities/tenaris?cid=13302
https://es.investing.com/equities/petrobras-on?cid=13303
https://es.investing.com/equities/banco-santander?cid=13369
https://es.investing.com/equities/telefonica?cid=13370
https://es.investing.com/equities/tran-gas-norte
https://es.investing.com/equities/chevron-corp-ar
https://es.investing.com/equities/citigroup-incorporated
https://es.investing.com/equities/bank-of-america-corp
https://es.investing.com/equities/at-t-inc.
https://es.investing.com/equities/intel-ar
https://es.investing.com/equities/jpmorgan-chase---co.
https://es.investing.com/equities/mcdonald-corp
https://es.investing.com/equities/merck---co-inc.
https://es.investing.com/equities/3m-co-drc
https://es.investing.com/equities/siemens-a.g.
https://es.investing.com/equities/bhp-ltd
https://es.investing.com/equities/colgate-palmolive-company
https://es.investing.com/equities/du-pont-de-nemours---company
https://es.investing.com/equities/wal-mart-stores-inc
https://es.investing.com/equities/home-depot-inc.
https://es.investing.com/equities/international-business-machines
https://es.investing.com/equities/sony?cid=30229
https://es.investing.com/equities/verizon-communications-inc.
https://es.investing.com/equities/newmont-mining-drc
https://es.investing.com/equities/johnson---johnson-co
https://es.investing.com/equities/general-electric-co.
https://es.investing.com/equities/toyota?cid=30284
https://es.investing.com/equities/pepsico-inc
https://es.investing.com/equities/petrochina-co
https://es.investing.com/equities/nike-inc
https://es.investing.com/equities/procter---gamble
https://es.investing.com/equities/vale-s.a.--americ?cid=30353
https://es.investing.com/equities/banco-bradesco-adr?cid=30418
https://es.investing.com/equities/goldcorp
https://es.investing.com/equities/ovoprot-international-sa
https://es.investing.com/equities/havanna-sa
https://es.investing.com/equities/meranol-saci
https://es.investing.com/equities/cablevision
https://es.investing.com/equities/laboratorios-richmond